-- 在 postgres 数据库中使用管理员账号执行。
-- 把 REPLACE_WITH_ENV_PASSWORD 替换为 .env 中的 POSTGRES_PASSWORD。
-- CREATE DATABASE 不能在事务块中执行，请勿开启事务模式。

CREATE ROLE lob_mcp
    WITH LOGIN
    PASSWORD 'REPLACE_WITH_ENV_PASSWORD'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

CREATE DATABASE lob_mcp
    WITH OWNER = lob_mcp
    ENCODING = 'UTF8'
    TEMPLATE = template0;

REVOKE ALL ON DATABASE lob_mcp FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE lob_mcp TO lob_mcp;
