import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";

type Server={id:string;name:string;transport:"stdio"|"http";endpoint?:string;command?:string[];headers:Record<string,string>;credential_reference?:string;enabled:boolean;runtime_status:string;last_error?:string};
type Tool={name:string;description:string;inputSchema:unknown;serverId?:string;server?:string};
type Invocation={id:string;server_id?:string;capability_name:string;arguments:unknown;result?:unknown;status:string;trace_id:string;duration_ms?:number;started_at:string;error_message?:string;cancel_requested:boolean};
type Approval={id:string;invocation_id:string;tool_name:string;risk_level:string;requested_arguments:Record<string,unknown>;status:string;operator?:string;created_at:string};
type Tab="servers"|"tools"|"approvals"|"audit";

async function api<T>(path:string,options?:RequestInit):Promise<T>{const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error(await r.text());return r.status===204?undefined as T:r.json()}

export default function App(){
 const [tab,setTab]=useState<Tab>("servers"),[servers,setServers]=useState<Server[]>([]),[tools,setTools]=useState<Tool[]>([]),[calls,setCalls]=useState<Invocation[]>([]),[approvals,setApprovals]=useState<Approval[]>([]);
 const [error,setError]=useState(""),[selected,setSelected]=useState<unknown>(),[status,setStatus]=useState(""),[capability,setCapability]=useState("");
 const refresh=useCallback(async()=>{try{const q=new URLSearchParams();if(status)q.set("status",status);if(capability)q.set("capability",capability);const [s,t,i,a]=await Promise.all([api<Server[]>("/api/servers"),api<Tool[]>("/api/tools"),api<Invocation[]>(`/api/invocations?${q}`),api<Approval[]>("/api/approvals")]);setServers(s);setTools(t);setCalls(i);setApprovals(a);setError("")}catch(e){setError(String(e))}},[status,capability]);
 useEffect(()=>{void refresh()},[refresh]);
 return <main><header><div><span className="eyebrow">LOB AI 源码研究</span><h1>MCP 运行控制台</h1></div><button className="secondary" onClick={()=>void refresh()}>刷新数据</button></header>
 {error&&<div className="error">{error}</div>}
 <section className="metrics"><Metric label="Server" value={servers.length}/><Metric label="Ready" value={servers.filter(x=>x.runtime_status==="ready").length}/><Metric label="调用" value={calls.length}/><Metric label="待审批" value={approvals.filter(x=>x.status==="pending").length}/></section>
 <nav>{(["servers","tools","approvals","audit"] as Tab[]).map(x=><button key={x} className={tab===x?"active secondary":"secondary"} onClick={()=>setTab(x)}>{{servers:"Server 管理",tools:"能力与调用",approvals:"审批中心",audit:"调用审计"}[x]}</button>)}</nav>
 {tab==="servers"&&<Servers servers={servers} refresh={refresh} inspect={async id=>setSelected(await api(`/api/servers/${id}/capabilities`))}/>}
 {tab==="tools"&&<Tools tools={tools} refresh={refresh} setError={setError} setSelected={setSelected}/>}
 {tab==="approvals"&&<Approvals approvals={approvals} refresh={refresh} setError={setError}/>}
 {tab==="audit"&&<Audit calls={calls} status={status} capability={capability} setStatus={setStatus} setCapability={setCapability} inspect={async id=>setSelected(await api(`/api/invocations/${id}`))} refresh={refresh}/>}
 {selected!==undefined&&<Drawer close={()=>setSelected(undefined)} value={selected}/>}</main>
}

function Servers({servers,refresh,inspect}:{servers:Server[];refresh:()=>Promise<void>;inspect:(id:string)=>void}){
 type ServerForm={name:string;transport:"stdio"|"http";endpoint:string;command:string;credential_reference:string};
 const empty:ServerForm={name:"",transport:"stdio",endpoint:"",command:'[".venv/bin/python","-m","lob_mcp.cli","serve-stdio"]',credential_reference:""};const [form,setForm]=useState<ServerForm>(empty),[editing,setEditing]=useState<string>();
 const submit=async(e:FormEvent)=>{e.preventDefault();const body={name:form.name,transport:form.transport,endpoint:form.endpoint||null,command:form.transport==="stdio"?JSON.parse(form.command):null,headers:{},credential_reference:form.credential_reference||null,enabled:true};await api(editing?`/api/servers/${editing}`:"/api/servers",{method:editing?"PUT":"POST",body:JSON.stringify(body)});setForm(empty);setEditing(undefined);await refresh()};
 const edit=(x:Server)=>{setEditing(x.id);setForm({name:x.name,transport:x.transport,endpoint:x.endpoint||"",command:JSON.stringify(x.command||[]),credential_reference:x.credential_reference||""})};
 return <div className="grid"><section className="panel"><Title title="Server 注册表" sub="动态连接、启停、刷新和软删除"/><Table heads={["名称","Transport","运行状态","操作"]}>{servers.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.last_error||x.endpoint||x.command?.join(" ")}</small></td><td><code>{x.transport}</code></td><td><Status value={x.runtime_status}/></td><td className="actions"><button onClick={()=>inspect(x.id)}>能力</button><button className="secondary" onClick={()=>edit(x)}>编辑</button><button className="secondary" onClick={async()=>{await api(`/api/servers/${x.id}/enabled?enabled=${!x.enabled}`,{method:"POST"});await refresh()}}>{x.enabled?"停用":"启用"}</button><button className="danger" onClick={async()=>{await api(`/api/servers/${x.id}`,{method:"DELETE"});await refresh()}}>删除</button></td></tr>)}</Table></section>
 <section className="panel form-panel"><Title title={editing?"编辑 Server":"注册 Server"} sub="stdio command 或 Streamable HTTP endpoint"/><form onSubmit={submit}><label>名称<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Transport<select value={form.transport} onChange={e=>setForm({...form,transport:e.target.value as "stdio"|"http"})}><option>stdio</option><option>http</option></select></label>{form.transport==="stdio"?<label>Command JSON<textarea value={form.command} onChange={e=>setForm({...form,command:e.target.value})}/></label>:<label>Endpoint<input value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})}/></label>}<label>凭据引用<input value={form.credential_reference} onChange={e=>setForm({...form,credential_reference:e.target.value})} placeholder="cred_...（可选）"/></label><button>{editing?"保存并重连":"注册并连接"}</button></form></section></div>
}

function Tools({tools,refresh,setError,setSelected}:{tools:Tool[];refresh:()=>Promise<void>;setError:(x:string)=>void;setSelected:(x:unknown)=>void}){const [tool,setTool]=useState("order.query"),[serverId,setServerId]=useState(""),[args,setArgs]=useState('{"order_id":"ORD-20250902-001"}');const selected=tools.find(x=>x.name===tool&&(!serverId||x.serverId===serverId));const call=async(e:FormEvent)=>{e.preventDefault();try{const result=await api("/api/tools/call",{method:"POST",body:JSON.stringify({name:tool,arguments:JSON.parse(args),server_id:serverId||null})});setSelected(result);await refresh()}catch(err){setError(String(err))}};return <div className="grid"><section className="panel"><Title title="能力目录" sub="来自最新 CapabilitySnapshot"/><Table heads={["Server","工具","说明"]}>{tools.map((x,i)=><tr key={`${x.serverId}-${x.name}-${i}`} onClick={()=>{setTool(x.name);setServerId(x.serverId||"")}}><td>{x.server||"内置"}</td><td><strong>{x.name}</strong></td><td>{x.description}</td></tr>)}</Table></section><section className="panel form-panel"><Title title="在线调用" sub={selected?.description||"选择工具并填写 JSON 参数"}/><form onSubmit={call}><label>工具<input value={tool} onChange={e=>setTool(e.target.value)}/></label><label>Server ID<input value={serverId} onChange={e=>setServerId(e.target.value)} placeholder="留空调用内置示例"/></label><label>参数 JSON<textarea value={args} onChange={e=>setArgs(e.target.value)}/></label><button>执行工具</button></form></section></div>}

function Approvals({approvals,refresh,setError}:{approvals:Approval[];refresh:()=>Promise<void>;setError:(x:string)=>void}){const decide=async(x:Approval,approved:boolean)=>{try{await api(`/api/approvals/${x.id}/decision`,{method:"POST",body:JSON.stringify({approved,operator:"console-user",revised_arguments:x.requested_arguments})});await refresh()}catch(e){setError(String(e))}};return <section className="panel"><Title title="审批中心" sub="高风险工具未经批准不会执行"/><Table heads={["时间","工具","风险","状态","操作"]}>{approvals.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><strong>{x.tool_name}</strong></td><td><Status value={x.risk_level}/></td><td><Status value={x.status}/></td><td className="actions">{x.status==="pending"&&<><button onClick={()=>void decide(x,true)}>批准</button><button className="danger" onClick={()=>void decide(x,false)}>拒绝</button></>}</td></tr>)}</Table></section>}

function Audit({calls,status,capability,setStatus,setCapability,inspect,refresh}:{calls:Invocation[];status:string;capability:string;setStatus:(x:string)=>void;setCapability:(x:string)=>void;inspect:(id:string)=>void;refresh:()=>Promise<void>}){return <section className="panel"><Title title="调用审计" sub="筛选、详情时间线与运行中取消"/><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{["running","awaiting_approval","succeeded","failed","cancelled","rejected"].map(x=><option key={x}>{x}</option>)}</select><input value={capability} onChange={e=>setCapability(e.target.value)} placeholder="筛选能力名"/></div><Table heads={["时间","能力","状态","耗时","Trace","操作"]}>{calls.map(x=><tr key={x.id}><td>{new Date(x.started_at).toLocaleString()}</td><td>{x.capability_name}</td><td><Status value={x.status}/></td><td>{x.duration_ms?.toFixed(1)??"—"} ms</td><td><code>{x.trace_id.slice(0,12)}</code></td><td className="actions"><button className="secondary" onClick={()=>inspect(x.id)}>详情</button>{x.status==="running"&&<button className="danger" onClick={async()=>{await api(`/api/invocations/${x.id}/cancel`,{method:"POST"});await refresh()}}>取消</button>}</td></tr>)}</Table></section>}

function Drawer({close,value}:{close:()=>void;value:unknown}){return <div className="overlay" onClick={close}><aside onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>详情</h2><button className="secondary" onClick={close}>关闭</button></div><pre>{JSON.stringify(value,null,2)}</pre></aside></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value}</span>}
function Title({title,sub}:{title:string;sub:string}){return <div className="panel-title"><h2>{title}</h2><p>{sub}</p></div>}
function Table({heads,children}:{heads:string[];children:ReactNode}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
